---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[8], line 212
    209 NUMERO = "277"
    210 DATA   = "2022-10-31"  # YYYY-MM-DD
--> 212 result = buscar_descritivo_no_dou(ORGAO, TIPO, NUMERO, DATA)
    213 print(json.dumps(result, ensure_ascii=False, indent=2))

Cell In[8], line 188, in buscar_descritivo_no_dou(orgao, tipo, numero, data_publicacao)
    185     pass
    187 # 2) Fallback: LexML (ementa) + eventualmente link oficial
--> 188 alt = _fallback_lexml(orgao, tipo, numero, data_publicacao)
    189 if alt:
    190     return {
    191         "titulo": alt["title"],
    192         "descritivo": alt["description"],
    193         "fonte_html": alt["html_url"],
    194         "fonte_pdf": alt["pdf_url"]
    195     }

Cell In[8], line 136, in _fallback_lexml(orgao, tipo, numero, data_publicacao)
    133 sru = ("https://www.lexml.gov.br/busca/SRU"
    134        "?operation=searchRetrieve&version=1.2&maximumRecords=5&query=" + ul.quote(cql))
    135 r = requests.get(sru, headers=HEADERS, timeout=30)
--> 136 r.raise_for_status()
    137 soup = BeautifulSoup(r.text, "lxml")
    138 rec = soup.find("recorddata")

File c:\Users\vinicius.silva\AppData\Local\conda\conda\envs\py_atualizado\Lib\site-packages\requests\models.py:1024, in Response.raise_for_status(self)
   1019     http_error_msg = (
   1020         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1021     )
   1023 if http_error_msg:
-> 1024     raise HTTPError(http_error_msg, response=self)

HTTPError: 500 Server Error: Internal Server Error for url: https://www.lexml.gov.br/busca/SRU?operation=searchRetrieve&version=1.2&maximumRecords=5&query=dc.title%20any%20%22Resolu%C3%A7%C3%A3o%20BCB%22%20and%20dc.title%20any%20%22277%22%20and%20date%20any%202022%20and%20dc.description%20any%20%22Banco%20Central%20do%20Brasil%22
